import type {
  AttendanceRow,
  Book,
  Exam,
  FeeRecord,
  LeaveRequest,
  LibraryIssue,
  PayrollRecord,
  SchoolBranding,
  StaffMember,
  Student,
  Teacher,
  User,
} from "./types";

export const DEMO_SCHOOL: SchoolBranding = {
  name: "Horizon International School",
  shortName: "Horizon",
  tagline: "Where curiosity meets excellence",
  logoText: "HI",
  primaryColor: "#0F6E56",
  accentColor: "#E8A838",
  subdomain: "horizon",
  customDomain: "portal.horizonschool.edu",
  address: "12 Knowledge Park, Pune, MH 411045",
  phone: "+91 98765 43210",
  email: "admin@horizonschool.edu",
};

export const DEMO_USERS: User[] = [
  {
    id: "u1",
    name: "Ananya Mehta",
    email: "admin@horizon.edu",
    role: "admin",
    department: "Administration",
  },
  {
    id: "u2",
    name: "Rahul Sharma",
    email: "rahul@horizon.edu",
    role: "teacher",
    department: "Science",
  },
  {
    id: "u3",
    name: "Priya Nair",
    email: "priya@horizon.edu",
    role: "student",
    className: "10-A",
  },
  {
    id: "u4",
    name: "Suresh Patil",
    email: "suresh@horizon.edu",
    role: "staff",
    department: "Accounts",
  },
];

export const STUDENTS: Student[] = [
  {
    id: "s1",
    name: "Priya Nair",
    rollNo: "10A-12",
    className: "10",
    section: "A",
    gender: "F",
    parentName: "Rajesh Nair",
    phone: "9876500001",
    email: "priya@student.edu",
    feesStatus: "paid",
    attendancePct: 94,
    status: "active",
  },
  {
    id: "s2",
    name: "Arjun Verma",
    rollNo: "10A-03",
    className: "10",
    section: "A",
    gender: "M",
    parentName: "Neha Verma",
    phone: "9876500002",
    email: "arjun@student.edu",
    feesStatus: "partial",
    attendancePct: 88,
    status: "active",
  },
  {
    id: "s3",
    name: "Meera Joshi",
    rollNo: "9B-21",
    className: "9",
    section: "B",
    gender: "F",
    parentName: "Amit Joshi",
    phone: "9876500003",
    email: "meera@student.edu",
    feesStatus: "due",
    attendancePct: 76,
    status: "active",
  },
  {
    id: "s4",
    name: "Kabir Singh",
    rollNo: "12C-07",
    className: "12",
    section: "C",
    gender: "M",
    parentName: "Simran Singh",
    phone: "9876500004",
    email: "kabir@student.edu",
    feesStatus: "paid",
    attendancePct: 97,
    status: "active",
  },
  {
    id: "s5",
    name: "Ishita Rao",
    rollNo: "8A-15",
    className: "8",
    section: "A",
    gender: "F",
    parentName: "Vikram Rao",
    phone: "9876500005",
    email: "ishita@student.edu",
    feesStatus: "paid",
    attendancePct: 91,
    status: "active",
  },
  {
    id: "s6",
    name: "Dev Kapoor",
    rollNo: "11B-09",
    className: "11",
    section: "B",
    gender: "M",
    parentName: "Pooja Kapoor",
    phone: "9876500006",
    email: "dev@student.edu",
    feesStatus: "due",
    attendancePct: 82,
    status: "active",
  },
];

export const TEACHERS: Teacher[] = [
  {
    id: "t1",
    name: "Rahul Sharma",
    employeeId: "T-101",
    subjects: ["Physics", "Math"],
    classes: ["10-A", "11-B", "12-C"],
    email: "rahul@horizon.edu",
    phone: "9876511001",
    status: "active",
  },
  {
    id: "t2",
    name: "Sneha Iyer",
    employeeId: "T-102",
    subjects: ["English", "Literature"],
    classes: ["9-A", "9-B", "10-A"],
    email: "sneha@horizon.edu",
    phone: "9876511002",
    status: "active",
  },
  {
    id: "t3",
    name: "Dr. Farhan Qureshi",
    employeeId: "T-103",
    subjects: ["Chemistry", "Biology"],
    classes: ["11-A", "12-A"],
    email: "farhan@horizon.edu",
    phone: "9876511003",
    status: "on-leave",
  },
  {
    id: "t4",
    name: "Kavita Deshmukh",
    employeeId: "T-104",
    subjects: ["History", "Civics"],
    classes: ["8-A", "9-A"],
    email: "kavita@horizon.edu",
    phone: "9876511004",
    status: "active",
  },
];

export const STAFF: StaffMember[] = [
  {
    id: "st1",
    name: "Suresh Patil",
    employeeId: "ST-01",
    role: "Accountant",
    department: "Accounts",
    email: "suresh@horizon.edu",
    phone: "9876522001",
    salary: 42000,
  },
  {
    id: "st2",
    name: "Lata Kulkarni",
    employeeId: "ST-02",
    role: "Librarian",
    department: "Library",
    email: "lata@horizon.edu",
    phone: "9876522002",
    salary: 35000,
  },
  {
    id: "st3",
    name: "Ramesh Yadav",
    employeeId: "ST-03",
    role: "Transport Manager",
    department: "Transport",
    email: "ramesh@horizon.edu",
    phone: "9876522003",
    salary: 38000,
  },
  {
    id: "st4",
    name: "Geeta More",
    employeeId: "ST-04",
    role: "HR Executive",
    department: "HR",
    email: "geeta@horizon.edu",
    phone: "9876522004",
    salary: 40000,
  },
];

export const FEES: FeeRecord[] = [
  {
    id: "f1",
    studentName: "Priya Nair",
    className: "10-A",
    amount: 45000,
    paid: 45000,
    dueDate: "2026-04-15",
    status: "paid",
    category: "Tuition",
  },
  {
    id: "f2",
    studentName: "Arjun Verma",
    className: "10-A",
    amount: 45000,
    paid: 25000,
    dueDate: "2026-04-15",
    status: "partial",
    category: "Tuition",
  },
  {
    id: "f3",
    studentName: "Meera Joshi",
    className: "9-B",
    amount: 40000,
    paid: 0,
    dueDate: "2026-03-30",
    status: "overdue",
    category: "Tuition",
  },
  {
    id: "f4",
    studentName: "Kabir Singh",
    className: "12-C",
    amount: 12000,
    paid: 12000,
    dueDate: "2026-05-01",
    status: "paid",
    category: "Lab",
  },
  {
    id: "f5",
    studentName: "Ishita Rao",
    className: "8-A",
    amount: 8000,
    paid: 0,
    dueDate: "2026-05-10",
    status: "pending",
    category: "Transport",
  },
];

export const EXAMS: Exam[] = [
  {
    id: "e1",
    name: "Unit Test 2",
    className: "10",
    subject: "Physics",
    date: "2026-05-12",
    maxMarks: 40,
    status: "upcoming",
  },
  {
    id: "e2",
    name: "Mid-Term",
    className: "11",
    subject: "Chemistry",
    date: "2026-04-28",
    maxMarks: 80,
    status: "ongoing",
  },
  {
    id: "e3",
    name: "Pre-Board",
    className: "12",
    subject: "Math",
    date: "2026-03-20",
    maxMarks: 100,
    status: "completed",
  },
  {
    id: "e4",
    name: "Weekly Quiz",
    className: "9",
    subject: "English",
    date: "2026-05-05",
    maxMarks: 20,
    status: "upcoming",
  },
];

export const ATTENDANCE: AttendanceRow[] = [
  {
    id: "a1",
    name: "Priya Nair",
    className: "10-A",
    present: 168,
    absent: 8,
    late: 3,
    percentage: 94,
  },
  {
    id: "a2",
    name: "Arjun Verma",
    className: "10-A",
    present: 158,
    absent: 18,
    late: 5,
    percentage: 88,
  },
  {
    id: "a3",
    name: "Meera Joshi",
    className: "9-B",
    present: 136,
    absent: 40,
    late: 4,
    percentage: 76,
  },
  {
    id: "a4",
    name: "Kabir Singh",
    className: "12-C",
    present: 174,
    absent: 4,
    late: 2,
    percentage: 97,
  },
];

export const LEAVES: LeaveRequest[] = [
  {
    id: "l1",
    name: "Dr. Farhan Qureshi",
    role: "Teacher",
    type: "Medical",
    from: "2026-04-28",
    to: "2026-05-02",
    reason: "Surgery recovery",
    status: "approved",
  },
  {
    id: "l2",
    name: "Sneha Iyer",
    role: "Teacher",
    type: "Casual",
    from: "2026-05-08",
    to: "2026-05-08",
    reason: "Family function",
    status: "pending",
  },
  {
    id: "l3",
    name: "Priya Nair",
    role: "Student",
    type: "Sick",
    from: "2026-05-01",
    to: "2026-05-03",
    reason: "Fever",
    status: "approved",
  },
  {
    id: "l4",
    name: "Ramesh Yadav",
    role: "Staff",
    type: "Earned",
    from: "2026-05-15",
    to: "2026-05-20",
    reason: "Personal travel",
    status: "pending",
  },
];

export const PAYROLL: PayrollRecord[] = [
  {
    id: "p1",
    name: "Rahul Sharma",
    role: "Teacher",
    basic: 55000,
    allowances: 8000,
    deductions: 4200,
    net: 58800,
    month: "April 2026",
    status: "paid",
  },
  {
    id: "p2",
    name: "Sneha Iyer",
    role: "Teacher",
    basic: 48000,
    allowances: 6000,
    deductions: 3800,
    net: 50200,
    month: "April 2026",
    status: "paid",
  },
  {
    id: "p3",
    name: "Suresh Patil",
    role: "Staff",
    basic: 35000,
    allowances: 5000,
    deductions: 2800,
    net: 37200,
    month: "April 2026",
    status: "processing",
  },
  {
    id: "p4",
    name: "Lata Kulkarni",
    role: "Staff",
    basic: 30000,
    allowances: 3500,
    deductions: 2400,
    net: 31100,
    month: "April 2026",
    status: "pending",
  },
];

export const BOOKS: Book[] = [
  {
    id: "b1",
    title: "Concepts of Physics Vol 1",
    author: "H.C. Verma",
    isbn: "978-8177091878",
    category: "Science",
    copies: 25,
    available: 12,
  },
  {
    id: "b2",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    isbn: "978-0061120084",
    category: "Literature",
    copies: 15,
    available: 8,
  },
  {
    id: "b3",
    title: "NCERT Mathematics Class 10",
    author: "NCERT",
    isbn: "978-8174506344",
    category: "Math",
    copies: 40,
    available: 22,
  },
  {
    id: "b4",
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    isbn: "978-0553380163",
    category: "Science",
    copies: 10,
    available: 3,
  },
];

export const LIBRARY_ISSUES: LibraryIssue[] = [
  {
    id: "li1",
    bookTitle: "Concepts of Physics Vol 1",
    borrower: "Arjun Verma",
    issueDate: "2026-04-10",
    dueDate: "2026-04-24",
    status: "overdue",
  },
  {
    id: "li2",
    bookTitle: "To Kill a Mockingbird",
    borrower: "Priya Nair",
    issueDate: "2026-04-22",
    dueDate: "2026-05-06",
    status: "issued",
  },
  {
    id: "li3",
    bookTitle: "A Brief History of Time",
    borrower: "Kabir Singh",
    issueDate: "2026-03-15",
    dueDate: "2026-03-29",
    status: "returned",
  },
];

export const DASHBOARD_STATS = {
  students: 1248,
  teachers: 86,
  staff: 42,
  feeCollected: 18450000,
  feePending: 2340000,
  attendanceToday: 92.4,
  libraryBooks: 8640,
  pendingLeaves: 7,
};

export const CLASS_PERFORMANCE = [
  { className: "8", avg: 78 },
  { className: "9", avg: 74 },
  { className: "10", avg: 81 },
  { className: "11", avg: 76 },
  { className: "12", avg: 83 },
];

export const SYLLABUS_TOPICS: Record<string, string[]> = {
  Physics: [
    "Laws of Motion",
    "Work, Energy and Power",
    "Gravitation",
    "Properties of Matter",
    "Thermodynamics",
    "Oscillations and Waves",
    "Electrostatics",
    "Current Electricity",
  ],
  Chemistry: [
    "Atomic Structure",
    "Chemical Bonding",
    "Thermodynamics",
    "Equilibrium",
    "Organic Chemistry Basics",
    "Hydrocarbons",
    "Periodic Table",
    "Solutions",
  ],
  Mathematics: [
    "Quadratic Equations",
    "Arithmetic Progressions",
    "Triangles",
    "Circles",
    "Coordinate Geometry",
    "Trigonometry",
    "Statistics",
    "Probability",
  ],
  English: [
    "Reading Comprehension",
    "Grammar - Tenses",
    "Letter Writing",
    "Essay Writing",
    "Poetry Analysis",
    "Prose - Character Study",
    "Vocabulary",
    "Story Writing",
  ],
  Biology: [
    "Cell Structure",
    "Plant Physiology",
    "Human Digestion",
    "Respiration",
    "Reproduction",
    "Genetics",
    "Ecology",
    "Evolution",
  ],
};
