<?php

$dictionary['BS_Orders'] = [
    'table' => 'bs_orders',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => false,
    'fields' => [
        'account_id' => [
            'name' => 'account_id',
            'type' => 'id',
            'vname' => 'LBL_ACCOUNT_ID',
            'reportable' => false,
        ],
        'account_name' => [
            'name' => 'account_name',
            'rname' => 'name',
            'id_name' => 'account_id',
            'vname' => 'LBL_ACCOUNT',
            'type' => 'relate',
            'link' => 'accounts',
            'table' => 'accounts',
            'module' => 'Accounts',
            'source' => 'non-db',
        ],
        'accounts' => [
            'name' => 'accounts',
            'type' => 'link',
            'relationship' => 'accounts_bs_orders',
            'source' => 'non-db',
            'vname' => 'LBL_ACCOUNT',
        ],
        'contact_id' => [
            'name' => 'contact_id',
            'type' => 'id',
            'vname' => 'LBL_CONTACT_ID',
            'reportable' => false,
        ],
        'contact_name' => [
            'name' => 'contact_name',
            'rname' => 'name',
            'id_name' => 'contact_id',
            'vname' => 'LBL_CONTACT',
            'type' => 'relate',
            'link' => 'contacts',
            'table' => 'contacts',
            'module' => 'Contacts',
            'source' => 'non-db',
        ],
        'contacts' => [
            'name' => 'contacts',
            'type' => 'link',
            'relationship' => 'contacts_bs_orders',
            'source' => 'non-db',
            'vname' => 'LBL_CONTACT',
        ],
        'service_id' => [
            'name' => 'service_id',
            'type' => 'id',
            'vname' => 'LBL_SERVICE_ID',
            'reportable' => false,
        ],
        'service_name' => [
            'name' => 'service_name',
            'rname' => 'name',
            'id_name' => 'service_id',
            'vname' => 'LBL_SERVICE',
            'type' => 'relate',
            'link' => 'bs_services',
            'table' => 'bs_services',
            'module' => 'BS_Services',
            'source' => 'non-db',
        ],
        'bs_services' => [
            'name' => 'bs_services',
            'type' => 'link',
            'relationship' => 'bs_services_bs_orders',
            'source' => 'non-db',
            'vname' => 'LBL_SERVICE',
        ],
        'status' => [
            'name' => 'status',
            'vname' => 'LBL_STATUS',
            'type' => 'enum',
            'options' => 'bs_order_status_list',
            'default' => 'application_submitted',
            'len' => 50,
            'audited' => true,
        ],
        'payment_status' => [
            'name' => 'payment_status',
            'vname' => 'LBL_PAYMENT_STATUS',
            'type' => 'enum',
            'options' => 'bs_payment_status_list',
            'default' => 'pending',
            'len' => 50,
            'audited' => true,
        ],
        'amount' => [
            'name' => 'amount',
            'vname' => 'LBL_AMOUNT',
            'type' => 'currency',
            'dbType' => 'decimal',
            'len' => '26,6',
        ],
        'gst_amount' => [
            'name' => 'gst_amount',
            'vname' => 'LBL_GST_AMOUNT',
            'type' => 'currency',
            'dbType' => 'decimal',
            'len' => '26,6',
        ],
        'total_amount' => [
            'name' => 'total_amount',
            'vname' => 'LBL_TOTAL_AMOUNT',
            'type' => 'currency',
            'dbType' => 'decimal',
            'len' => '26,6',
        ],
        'assigned_at' => [
            'name' => 'assigned_at',
            'vname' => 'LBL_ASSIGNED_AT',
            'type' => 'datetime',
        ],
        'is_new_enquiry' => [
            'name' => 'is_new_enquiry',
            'vname' => 'LBL_IS_NEW_ENQUIRY',
            'type' => 'bool',
            'default' => '1',
            'comment' => 'Counts toward daily auto-assignment cap',
        ],
        'gstin' => [
            'name' => 'gstin',
            'vname' => 'LBL_GSTIN',
            'type' => 'varchar',
            'len' => 20,
        ],
        'pan' => [
            'name' => 'pan',
            'vname' => 'LBL_PAN',
            'type' => 'varchar',
            'len' => 20,
        ],
        'source' => [
            'name' => 'source',
            'vname' => 'LBL_SOURCE',
            'type' => 'varchar',
            'len' => 50,
            'default' => 'admin',
        ],
        'application_json' => [
            'name' => 'application_json',
            'vname' => 'LBL_APPLICATION_JSON',
            'type' => 'longtext',
        ],
    ],
    'relationships' => [
        'accounts_bs_orders' => [
            'lhs_module' => 'Accounts',
            'lhs_table' => 'accounts',
            'lhs_key' => 'id',
            'rhs_module' => 'BS_Orders',
            'rhs_table' => 'bs_orders',
            'rhs_key' => 'account_id',
            'relationship_type' => 'one-to-many',
        ],
        'contacts_bs_orders' => [
            'lhs_module' => 'Contacts',
            'lhs_table' => 'contacts',
            'lhs_key' => 'id',
            'rhs_module' => 'BS_Orders',
            'rhs_table' => 'bs_orders',
            'rhs_key' => 'contact_id',
            'relationship_type' => 'one-to-many',
        ],
        'bs_services_bs_orders' => [
            'lhs_module' => 'BS_Services',
            'lhs_table' => 'bs_services',
            'lhs_key' => 'id',
            'rhs_module' => 'BS_Orders',
            'rhs_table' => 'bs_orders',
            'rhs_key' => 'service_id',
            'relationship_type' => 'one-to-many',
        ],
    ],
    'indices' => [
        ['name' => 'idx_bs_orders_assigned_date', 'type' => 'index', 'fields' => ['assigned_user_id', 'date_entered']],
        ['name' => 'idx_bs_orders_status', 'type' => 'index', 'fields' => ['status']],
        ['name' => 'idx_bs_orders_name', 'type' => 'index', 'fields' => ['name']],
        ['name' => 'idx_bs_orders_pan', 'type' => 'index', 'fields' => ['pan']],
        ['name' => 'idx_bs_orders_gstin', 'type' => 'index', 'fields' => ['gstin']],
    ],
    'optimistic_locking' => true,
];

if (!class_exists('VardefManager')) {
    require_once 'include/SugarObjects/VardefManager.php';
}
VardefManager::createVardef('BS_Orders', 'BS_Orders', ['basic', 'assignable', 'security_groups']);
